* Lorn

What is it? Basically a quick check of k8s for orphaned resources or things that are "lost". For now that basically means orphaned pv/pvc's, bitnami images, and CSI volumes whose driver has no ~VolumeSnapshotClass~ or have no CSI driver that can support snapshots.

** Usage

Just download it and run it for the plaform you need. Its a static binary for windows/linux and a *mostly* static binary for macos aarch64 (note fully static binaries aren't technically allowed even if they are possible).

Note you will need to have *KUBECONFIG* set for this to work. There is no arg parsing right now so only the *KUBECONFIG* var controls where it looks for data.


Example run with an intentionally broken upstream k8s setup:

#+begin_src sh
$ lorn
orphaned pvc: default/orphan-test-pvc pv: pvc-02063219-9a71-418f-a3e6-f510142f2ed6
pod default/lorn-test-bitnami spec.containers[0].image: bitnami/redis:7.0.15
pod default/lorn-test-bitnami spec.containers[1].image: docker.io/bitnami/nginx:1.25.4
pod default/lorn-test-bitnami spec.initContainers[0].image: bitnami/kubectl:1.29
csi driver: rancher.io/local-path has no VolumeSnapshotClass pv: lorn-test-csi-noss-pv
zsh: exit 1     lorn
#+end_src

If nothing is found there should be no output and return code should be 0. If anything lorn or even forlorn is found the return code will be non zero and stdout should have the details about what it was.

** Validation

To test out that this finds what is expected, there is a `canary.yaml` file at the root of the repo that you may apply via kubectl:

#+begin_src sh
kubectl apply -f canary.yaml
#+end_src

Then you'll need to manually delete the pod associated with the pv/pvc claim to trigger the orphan detection:

#+begin_src sh
kubectl delete pod orphan-test-pod
#+end_src

Note for CSI snapshot provider testing the local path provisioner should be setup beforehand as per https://github.com/rancher/local-path-provisioner#installation

#+begin_src sh
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.36/deploy/local-path-storage.yaml
#+end_src

And you should basically get the output in this readme. Cleanup is the same as any other k8s resource:

#+begin_src sh
kubectl delete -f canary.yaml
#+end_src

** Why only rust?

A prior version of lorn shipped a parallel `lorn.sh` shell implementation using kubectl and jq for folks who didn't trust binaries built on github actions. It has been dropped: doing the same work serially via kubectl/sh/pipes has real fork()/exec() and more importantly sanity trying to use jq cost that adds up, and the shell logic needed to keep pace with the Rust implementation owner resolution, securityContext aware checks, etc. was no longer worth the added maintenance burden. If you need to build from source and don't trust prebuilt binaries, build the Rust binary locally.
