[package]
name = "lorn"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lorn"
path = "src/main.rs"

[dependencies]
clap.workspace = true
futures.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
